# Generated by Django 4.0.6 on 2022-07-27 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_rename_select_user_letterreviewlike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterreviewlike',
            name='letter_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.letterreview'),
        ),
    ]
