# Generated by Django 4.0.6 on 2022-08-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0008_alter_letterreviewlike_letter_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterreview",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
