# Generated by Django 4.0.6 on 2022-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0010_letter_color_letter_font_family_letter_font_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="color",
            field=models.CharField(default="rgb(0, 0, 0)", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="font_family",
            field=models.CharField(default="Gamja Flower, cursive", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="letter",
            name="font_size",
            field=models.CharField(default="23.44px", max_length=30, null=True),
        ),
    ]
