version: '3.9'
services:
  mail_box:
    build: .
    command: python manage.py migrate && python manage.py runserver
    ports:
      - 8000:8000
    working_dir: /app/
    volumes:
      - ./:/app/
    env_file:
      - ./.env.dev
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: mysql:8.0.25
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "mail_box"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql_db: