version: '3.9'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_server
  web_server:
    image: aboutjoo/mail_box:latest
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    working_dir: /app/
    command: gunicorn --bind 0.0.0.0:8000 --workers=5 mail_box.wsgi:application  &
    volumes:
      - ./:/app/
      - static_volume:/app/static
    expose:
      - 8000
volumes:
  static_volume:
