version: '3.9'
services:
  mail_box:
    image: aboutjoo/mail_box:latest
    env_file:
      - "/home/ubuntu/.env"
    ports:
      - "80:8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers=5 mail_box.wsgi:application  &
