version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis_service
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redisdata:/data
  web_server:
    image: aboutjoo/mail_box:latest
    env_file:
      - ./.env.prod
    ports:
      - "80:8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers=5 mail_box.wsgi:application  &
    working_dir: /app/
    depends_on:
      - redis