version: '3.9'
services:
  redis_service:
    image: redis:alpine
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/data
  mail_box:
    env_file:
      - .env
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    expose:
      - 8000
    depends_on:
      - redis_service
      - db
      - elasticsearch
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MONGLE_PASSWORD}
      MYSQL_DATABASE: ${MONGLE_DB_NAME}
    cap_add:
      - SYS_NICE
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    depends_on:
      - db
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      ELASTIC_PASSWORD: ${MONGLE_ES_PASSWORD}
  logstash:
    env_file:
      - .env
    build:
      context: .
      dockerfile: logstash/Dockerfile
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: .
      dockerfile: kibana/Dockerfile
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch:
  db:
  redisdata: