# Generated by Django 4.0.6 on 2022-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpush", "0002_auto_20190603_0005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="pushinformation",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="subscriptioninfo",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
