# Generated by Django 4.0.6 on 2022-07-12 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('won_test', '0001_initial'),
        ('jin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='won_test.user'),
        ),
        migrations.AlterField(
            model_name='letter_review',
            name='review_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='won_test.user'),
        ),
        migrations.AlterField(
            model_name='letter_review_like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='won_test.user'),
        ),
        migrations.AlterField(
            model_name='user_letter_target_user',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='won_test.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
