# Generated by Django 4.0.6 on 2022-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="사용자 계정"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                ("nickname", models.CharField(max_length=20, verbose_name="닉네임")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
