# Generated by Django 4.0.6 on 2022-07-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorryBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=90, verbose_name="내용")),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.worrycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_message",
                    models.TextField(max_length=120, verbose_name="요청 메세지"),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worry_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worry_board.worryboard",
                    ),
                ),
            ],
        ),
    ]
