# Generated by Django 4.0.6 on 2022-07-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_letterreviewlike_letter_review_and_more'),
        ('worry_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worryboard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.worrycategory'),
        ),
    ]
