# Generated by Django 4.0.6 on 2022-07-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worry_board", "0003_requeststatus_worryboard_request_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worryboard",
            name="request_status",
        ),
        migrations.AddField(
            model_name="requeststatus",
            name="worry_board",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="worry_board.worryboard"
            ),
        ),
    ]
