# Generated by Django 4.0.6 on 2022-07-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worry_board", "0005_remove_requeststatus_worry_board_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worryboard",
            name="request_status",
        ),
        migrations.AddField(
            model_name="requestmessage",
            name="request_status",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="worry_board.requeststatus"
            ),
        ),
    ]
