# Generated by Django 4.0.6 on 2022-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worry_board", "0006_remove_worryboard_request_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmessage",
            name="can_write_letter",
            field=models.BooleanField(default=False),
        ),
    ]
