# Generated by Django 4.0.6 on 2022-08-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worry_board", "0007_requestmessage_can_write_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmessage",
            name="request_message",
            field=models.TextField(max_length=180, verbose_name="요청 메세지"),
        ),
    ]
