# Generated by Django 4.0.6 on 2022-08-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worry_board", "0008_alter_requestmessage_request_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailWorryMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(max_length=500, verbose_name="상세내용")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "request_message",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="worry_board.requestmessage"),
                ),
            ],
        ),
    ]
