# Generated by Django 4.0.6 on 2022-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jin", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="categories",
            field=models.ManyToManyField(
                through="user.UserProfileCategory", to="jin.worrycategory"
            ),
        ),
    ]
