# Generated by Django 4.0.6 on 2022-07-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0008_alter_letterreviewlike_letter_review_and_more"),
        ("user", "0002_report_only_one_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilecategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_page.worrycategory",
            ),
        ),
    ]
