# Generated by Django 4.0.6 on 2022-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofilecategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_img",
            field=models.URLField(
                default="https://user-images.githubusercontent.com/55477835/181186077-f2c8d0ce-d92a-46d8-b0cb-8c931754c663.png"
            ),
        ),
    ]
