# Generated by Django 4.0.6 on 2022-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userprofile_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="received_letter_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="sent_letter_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
