# Generated by Django 4.0.6 on 2022-07-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_received_letter_cnt_user_sent_letter_cnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="mongle_grade",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mongle_level",
        ),
        migrations.AddField(
            model_name="monglegrade",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
