# Generated by Django 4.0.6 on 2022-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_userprofile_mongle_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monglegrade",
            name="mongle",
            field=models.URLField(
                default="https://user-images.githubusercontent.com/55477835/181283419-20705c71-a20a-46ab-a30e-bb4edece1670.png"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_img",
            field=models.URLField(
                default="https://user-images.githubusercontent.com/55477835/181283419-20705c71-a20a-46ab-a30e-bb4edece1670.png"
            ),
        ),
    ]
