# Generated by Django 4.0.6 on 2022-08-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_monglegrade_mongle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=20, verbose_name="닉네임"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, verbose_name="비밀번호"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name="사용자 계정"),
        ),
    ]
