# Generated by Django 4.0.6 on 2022-08-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_nickname_alter_user_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongleLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.IntegerField(default=1)),
                (
                    "mongle_image",
                    models.URLField(
                        default="https://user-images.githubusercontent.com/55477835/181283419-20705c71-a20a-46ab-a30e-bb4edece1670.png"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="monglegrade",
            name="level",
        ),
        migrations.RemoveField(
            model_name="monglegrade",
            name="mongle",
        ),
        migrations.AddField(
            model_name="monglegrade",
            name="mongle_level",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.monglelevel"),
        ),
    ]
