# Generated by Django 4.0.6 on 2022-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_monglelevel_remove_monglegrade_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monglelevel",
            name="mongle_image",
            field=models.URLField(
                default="https://user-images.githubusercontent.com/55477835/183033723-5d7dc862-add3-4fc2-80e6-7cd5b90fce54.png"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_img",
            field=models.URLField(
                default="https://user-images.githubusercontent.com/55477835/183034958-de0d010a-a105-459b-9d7b-915c04a882c7.png"
            ),
        ),
    ]
