# Generated by Django 4.0.6 on 2022-08-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_monglelevel_mongle_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("certification_question", models.TextField(max_length=40, verbose_name="본인인증 질문")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="certification_answer",
            field=models.TextField(default="", max_length=30, verbose_name="본인인증 답변"),
        ),
        migrations.AddField(
            model_name="user",
            name="certification_question",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.certificationquestion"
            ),
        ),
    ]
