# Generated by Django 4.0.6 on 2022-08-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_certificationquestion_user_certification_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificationquestion",
            old_name="certification_question",
            new_name="question",
        ),
    ]
