# Generated by Django 4.0.6 on 2022-08-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_certification_question_certificationquestion_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificationquestion",
            old_name="question",
            new_name="certification_question",
        ),
    ]
