# Generated by Django 4.0.6 on 2022-07-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worry_board', '0001_initial'),
        ('jin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='worryboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worry_board.worryboard'),
            preserve_default=False,
        ),
    ]
