# Generated by Django 4.0.6 on 2022-07-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jin", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letter",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userlettertargetuser",
            name="target_user",
        ),
    ]
