# Generated by Django 4.0.6 on 2022-07-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jin", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="letterreviewlike",
            old_name="review_id",
            new_name="letter_review",
        ),
        migrations.RenameField(
            model_name="letterreviewlike",
            old_name="user_id",
            new_name="user",
        ),
    ]
