# Generated by Django 4.0.6 on 2022-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
