# Generated by Django 4.0.6 on 2022-07-13 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jin', '0004_rename_letter_review_letterreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterreview',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
