# Generated by Django 4.0.6 on 2022-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('author', 'id'), name='user_only_one_board'),
        ),
        migrations.AddConstraint(
            model_name='boardlike',
            constraint=models.UniqueConstraint(fields=('author', 'board'), name='user_only_one_board_like'),
        ),
    ]
