# Generated by Django 4.0.6 on 2022-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boardlike',
            constraint=models.UniqueConstraint(fields=('author', 'board'), name='user_only_one_board_like'),

        ),
    ]
