name: mail_box_pipline
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      MONGLE_SECRET_KEY: ${{ secrets.MONGLE_SECRET_KEY }}
      MONGLE_JWT_SECRET_KEY: ${{ secrets.MONGLE_JWT_SECRET_KEY }}
      MONGLE_USER: ${{ secrets.MONGLE_USER }}
      MONGLE_DB_NAME: ${{ secrets.MONGLE_DB_NAME }}
      MONGLE_PASSWORD: ${{ secrets.MONGLE_PASSWORD }}
      MONGLE_HOST: ${{ secrets.MONGLE_HOST }}
      MONGLE_PORT: ${{ secrets.MONGLE_PORT }}
    steps:
      - uses: actions/checkout@master
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: run tests
        run: |
          python manage.py test

  build-image:
    needs: run-test
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mail_box:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  cd-pipeline:
    needs: build-image
    name: continuos deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: "docker compose pull && docker compose up -d"
